name = "NeuralImagingNetworks"
uuid = "0ef86b2b-c763-4eee-8501-d9b219021374"
authors = ["Tobias Knopp <tobias.knopp@tuhh.de> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
